SELECT CATEGORY_ID FROM CATEGORIES WHERE CATEGORY = "BACK";
SELECT * FROM  EXERCISE_INFORMATION WHERE CATEGORY_ID = 21;

SELECT * FROM USER_DIARIES WHERE USER_ID = 1 AND DIARY_ID = 2;

SELECT * FROM EXERCISE_HISTORY INNER JOIN EXERCISE_INFORMATION ON EXERCISE_INFORMATION.EXERCISE_ID = EXERCISE_HISTORY.EXERCISE_ID INNER JOIN CATEGORIES ON EXERCISE_INFORMATION.CATEGORY_ID = CATEGORIES.CATEGORY_ID  WHERE DIARY_ID = 1;

SELECT * FROM EXERCISE_HISTORY INNER JOIN EXERCISE_INFORMATION ON EXERCISE_INFORMATION.EXERCISE_ID = EXERCISE_HISTORY.EXERCISE_ID INNER JOIN CATEGORIES ON EXERCISE_INFORMATION.CATEGORY_ID = CATEGORIES.CATEGORY_ID  WHERE DIARY_ID = 1 AND EXERCISE_DATE = "2023-11-02 00:00:00";