USE WORKITWISE;

CREATE TABLE USERS(
	USER_NAME VARCHAR(30) NOT NULL,
    USER_EMAIL VARCHAR(40) PRIMARY KEY NOT NULL,
    USER_PASSWORD VARCHAR(30) NOT NULL
);

SELECT * FROM USERS;

INSERT INTO USERS VALUES(
	"Shashwat Singh",
    "vnsshashwat@gmail.com",
    "Qwerty"
);

