USE WORKITWISE;

DROP TABLE USERS;

CREATE TABLE USERS(
	USER_NAME VARCHAR(30) NOT NULL,
    USER_EMAIL VARCHAR(40) PRIMARY KEY NOT NULL,
    USER_PASSWORD VARCHAR(30) NOT NULL
);

SELECT * FROM USERS;

INSERT INTO USERS VALUES(
	"Shashwat Singh",
    "vnsshashwat@gmail.com",
    "Qwerty"
);

SELECT USER_PASSWORD FROM USERS WHERE USER_EMAIL = "email" AND USER_PASSWORD = "passw";

SELECT * FROM USERS WHERE USER_EMAIL = "test@gmail.com" AND USER_PASSWORD = "password";

ALTER TABLE USERS MODIFY COLUMN USER_PASSWORD VARCHAR(100) NOT NULL;

SELECT USER_NAME FROM USERS WHERE USER_EMAIL = "test@gmail.com";


-- exercies categories table
-- image, category





