-- default value: null


												-- repsXsets
-- assisted
-- band
-- barbell
-- body weight
-- bosu ball
-- cable 
-- dumbbell
-- ez barbell
-- kettlebell
-- leverage machine
-- medicine ball
-- olympic barbell
-- resistance band
-- roller
-- rope
-- skierg machine
-- sled machine
-- smith machine
-- stability ball
-- tire
-- trap bar
-- upper body ergometer
-- weighted
-- wheel roller
-- hammer
					-- minutes
-- elliptical machine
-- stationary bike
-- stepmill machine